-- MySQL Script generated by MySQL Workbench
-- Mon Feb  1 17:34:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pupsims_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pupsims_db` ;

-- -----------------------------------------------------
-- Schema pupsims_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pupsims_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pupsims_db` ;

-- -----------------------------------------------------
-- Table `pupsims_db`.`attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pupsims_db`.`attendance` ;

CREATE TABLE IF NOT EXISTS `pupsims_db`.`attendance` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `security_guard_id` BIGINT NOT NULL,
  `log_date` DATE NOT NULL,
  `log_status` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Main application user
-- -----------------------------------------------------
DROP USER 'pupsims'@'localhost';
CREATE USER 'pupsims'@'localhost' IDENTIFIED BY 'pupsimspass_123';
GRANT ALL PRIVILEGES ON `pupsims_db`.* TO 'pupsims'@'localhost'